---
- name: 'Save config to ~/backup'
  connection: network_cli
  gather_facts: false
  hosts: "{{ routers }}"
  tasks:
    - name: 'Get ansible date/time facts'
      ansible.builtin.setup:
        filter: ansible_date_time
        gather_subset: '!all'
        
    - name: backup
      ios_config:
        backup: yes
        backup_options:
          dir_path: /home/vadim/Ansible_books/backup/{{ ansible_date_time.date }}