- name: "Changed tunnels setting's"
  hosts: Brest_routers
  gather_facts: no
  ignore_errors: false
    
  tasks:

   - name: Retrieve the current L3 interface configuration
     cisco.ios.ios_l3_interfaces:
       state: gathered
     register: current_l3

   - name: Set commands to tunnel
     cisco.ios.ios_config:
       lines:
        - cdp enable
       parents: interface {{ current_l3.gathered[item].name }}
     
#     loop: "{{ lookup('ansible.utils.index_of', current_l3.gathered, 'regex', '^Tunnel7[012][0-9]$', 'name', wantlist=True) }} "  #Могилевская область
#     loop: "{{ lookup('ansible.utils.index_of', current_l3.gathered, 'regex', '^Tunnel[45]$', 'name', wantlist=True) }} "  #Витебская область
#     loop: "{{ lookup('ansible.utils.index_of', current_l3.gathered, 'regex', '^Tunnel30024[0-9]$', 'name', wantlist=True) }} "  #Гомельская область
#     loop: "{{ lookup('ansible.utils.index_of', current_l3.gathered, 'regex', '^Tunnel4[0]{0,1}$', 'name', wantlist=True) }} "  #Гродненская область
     loop: "{{ lookup('ansible.utils.index_of', current_l3.gathered, 'regex', '^Tunnel1[01]$', 'name', wantlist=True) }} "  #Брестская область