---
- name: create users from csv file
  hosts: local
  tasks:
   - name: reading the csv file
     read_csv:
      path: userID.csv
     register: user_list
     delegate_to: localhost

   - name: create users from the csv
     user:
      name: "{{ item.Username }}"
      uid: "{{ item.UID }}"
      groups: "{{ item.Groups }}"
      append: yes
      password: "{{ item.Password | password_hash('sha512') }}"
      comment: "{{ item.First_Name }} {{ item.Last_Name }}"
      state: present
     loop: "{{ user_list.list }}"
     become: true